# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with dotnet
      run: dotnet test --logger trx --results-directory "TestResults"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results.xlm
        path: TestResults
        retention-days: 1
      if: ${{ always() }}
    - name: Download dotnet test results
      uses: actions/download-artifact@v3
      with:
        name: dotnet-results.xlm
        path: TestResults
      if: ${{ always() }}
    - name: Extract test data 
      run: |
        value=`cat dotnet-results.xlm`
        expr $value 'total="([0-9]+)" executed="([0-9]+)" passed="([0-9]+)" failed="([0-9]+)"' dotnet-results.txt
        pattern='total="([0-9]+)" executed="([0-9]+)" passed="([0-9]+)" failed="([0-9]+)"'
          if [[ "$xml_string" =~ $pattern ]]; then
          echo total="${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          echo executed="${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          echo passed="${BASH_REMATCH[3]}" >> $GITHUB_OUTPUT
          echo failed="${BASH_REMATCH[4]}" >> $GITHUB_OUTPUT
          echo "Total: $total, Executed: $executed, Passed: $passed, Failed: $failed"
          else
          echo "No match found."
          fi
      shell: bash
      if: ${{ always() }}
      
